import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import importPlugin from 'eslint-plugin-import';
import vuePlugin from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**'
    ]
  },

  js.configs.recommended,

  {
    files: ['**/*.js', '**/*.jsx'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        browser: true,
        document: 'readonly',
        window: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        CanvasGradient: 'readonly',
        HTMLImageElement: 'readonly',
        Image: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        console: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        NaN: 'readonly',
        Infinity: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Boolean: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        Symbol: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        URL: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        Event: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        SVGElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        DOMTokenList: 'readonly',
        Text: 'readonly',
        Comment: 'readonly',
        Document: 'readonly',
        DocumentFragment: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        CanvasGradient: 'readonly',
        CanvasPattern: 'readonly',
        Image: 'readonly',
        ImageData: 'readonly',
        File: 'readonly',
        FileList: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        PerformanceObserver: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly'
      }
    },
    plugins: {
      import: importPlugin
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'import/order': [
        'warn',
        {
          groups: ['builtin', 'external', 'internal'],
          'newlines-between': 'always'
        }
      ],
      'no-case-declarations': 'error'
    }
  },

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module'
      },
      globals: {
        browser: true,
        document: 'readonly',
        window: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        CanvasGradient: 'readonly',
        HTMLImageElement: 'readonly',
        Image: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        console: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        NaN: 'readonly',
        Infinity: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Boolean: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        Symbol: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        URL: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        Event: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        SVGElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        DOMTokenList: 'readonly',
        Text: 'readonly',
        Comment: 'readonly',
        Document: 'readonly',
        DocumentFragment: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        CanvasPattern: 'readonly',
        ImageData: 'readonly',
        File: 'readonly',
        FileList: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        PerformanceObserver: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        structuredClone: 'readonly',
        WeakRef: 'readonly',
        FinalizationRegistry: 'readonly',
        BigInt: 'readonly',
        fetch: 'readonly',
        FileReader: 'readonly',
        Request: 'readonly',
        RequestInit: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        SVGFilterElement: 'readonly',
        SVGFETurbulenceElement: 'readonly',
        SVGFEDisplacementMapElement: 'readonly',
        SVGFEGaussianBlurElement: 'readonly',
        SVGAnimatedString: 'readonly',
        WebGLRenderingContext: 'readonly',
        WebGLFramebuffer: 'readonly',
        WebGLRenderbuffer: 'readonly',
        WebGLTexture: 'readonly',
        WebGLShader: 'readonly',
        WebGLProgram: 'readonly',
        WebGLUniformLocation: 'readonly',
        WebGLBuffer: 'readonly',
        WebGLActiveInfo: 'readonly',
        WebGLContextEvent: 'readonly',
        getComputedStyle: 'readonly',
        DOMParser: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLScriptElement: 'readonly',
        MutationRecord: 'readonly',
        MediaThumbnailEvent: 'readonly',
        MediaTimelineEvent: 'readonly',
        MediaPropertiesEvent: 'readonly',
        MediaPlaybackEvent: 'readonly',
        MediaStreamTrack: 'readonly',
        MediaDevices: 'readonly',
        MediaQueryList: 'readonly',
        matchMedia: 'readonly',
        devicePixelRatio: 'readonly',
        innerWidth: 'readonly',
        innerHeight: 'readonly',
        scrollX: 'readonly',
        scrollY: 'readonly',
        pageXOffset: 'readonly',
        pageYOffset: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileList: 'readonly',
        FormData: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        SharedWorker: 'readonly',
        ServiceWorker: 'readonly',
        ServiceWorkerContainer: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        PerformanceObserver: 'readonly',
        Performance: 'readonly',
        PerformanceEntry: 'readonly',
        PerformanceMark: 'readonly',
        PerformanceMeasure: 'readonly',
        Console: 'readonly',
        Error: 'readonly',
        EvalError: 'readonly',
        RangeError: 'readonly',
        ReferenceError: 'readonly',
        SyntaxError: 'readonly',
        TypeError: 'readonly',
        URIError: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        AddEventListenerOptions: 'readonly',
        EventListener: 'readonly',
        EventTarget: 'readonly',
        FocusEvent: 'readonly',
        InputEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        PointerEvent: 'readonly',
        TouchEvent: 'readonly',
        UIEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        MessageEvent: 'readonly',
        CloseEvent: 'readonly',
        BeforeUnloadEvent: 'readonly',
        PopStateEvent: 'readonly',
        HashChangeEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        FetchEvent: 'readonly',
        FormDataEvent: 'readonly',
        SubmitEvent: 'readonly',
        Touch: 'readonly',
        TouchList: 'readonly',
        NamedNodeMap: 'readonly',
        Attr: 'readonly',
        CDATASection: 'readonly',
        ProcessingInstruction: 'readonly',
        Entity: 'readonly',
        EntityReference: 'readonly',
        Notation: 'readonly',
        DocumentType: 'readonly',
        DOMStringMap: 'readonly',
        DatasetDOMStringMap: 'readonly',
        ValidityState: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        Text: 'readonly',
        Comment: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        DOMTokenList: 'readonly',
        DOMStringList: 'readonly',
        DOMImplementation: 'readonly',
        Document: 'readonly',
        DocumentFragment: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        HTMLUnknownElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLAreaElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLBaseElement: 'readonly',
        HTMLBodyElement: 'readonly',
        HTMLBRElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLTableCaptionElement: 'readonly',
        HTMLTableColElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLTemplateElement: 'readonly',
        HTMLQuoteElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLHeadElement: 'readonly',
        HTMLHtmlElement: 'readonly',
        HTMLHRElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLModElement: 'readonly',
        HTMLOrderedListElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLLinkElement: 'readonly',
        HTMLMetaElement: 'readonly',
        HTMLMeterElement: 'readonly',
        HTMLObjectElement: 'readonly',
        HTMLOptGroupElement: 'readonly',
        HTMLOptionElement: 'readonly',
        HTMLOutputElement: 'readonly',
        HTMLProgressElement: 'readonly',
        HTMLPropertyElement: 'readonly',
        HTMLScriptElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLSourceElement: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLLegendElement: 'readonly',
        HTMLFieldSetElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        decodeURI: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURI: 'readonly',
        encodeURIComponent: 'readonly',
        escape: 'readonly',
        unescape: 'readonly',
        atob: 'readonly',
        btoa: 'readonly'
      }
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'simple-import-sort': simpleImportSort
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_'
      }],
      'no-console': 'off',
      'no-unused-vars': 'off',
      'simple-import-sort/imports': 'warn',
      'simple-import-sort/exports': 'warn',
      'no-case-declarations': 'error',
      'no-useless-escape': 'off'
    }
  },

  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off'
    }
  },

  {
    files: ['tests/**/*.ts', 'vitest.config.ts'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        test: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        vitest: 'readonly'
      }
    }
  },

  // Vue SFC：启用 vue 规则集 + TS 解析 + 浏览器全局
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tsParser,
        ecmaVersion: 'latest',
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
      globals: {
        // 复用文件顶部已枚举的浏览器全局（避免 vue 块内大量 no-undef）
        // 这里用展开：eslint flatConfig 合并时 vue 块会继承上层 globals，
        // 但 vue-eslint-parser 默认不注入，需要显式声明
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLAudioElement: 'readonly',
        HTMLVideoElement: 'readonly',
        Image: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        InputEvent: 'readonly',
        FocusEvent: 'readonly',
        WheelEvent: 'readonly',
        DragEvent: 'readonly',
        MessageEvent: 'readonly',
        document: 'readonly',
        window: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        getComputedStyle: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
      },
    },
    plugins: {
      vue: vuePlugin,
    },
    rules: {
      // 基础推荐（template 段）
      ...vuePlugin.configs['flat/recommended'].rules,
      // 本项目定制：v-html 必须显式消毒，已在 Weather/Version 中处理
      'vue/no-v-html': 'warn',
      // 组件名单词数：项目历史命名为单字（Clock/Weather 等），先 warn 收敛
      'vue/multi-word-component-names': 'warn',
      // Vue SFC 内未使用变量走 vue 侧规则，与 TS 侧去重
      'no-unused-vars': 'off',
    },
  },

  prettier
];