export const audioVisualDefaults = {
    music_model: 0,
    music_volume: 0.5,
    selectmusic: '',
    musicdirectory: '',
    music_playlist: [] as string[],
    music_playlist_index: 0,
    music_playlist_random: false,
    music_playlist_repeat: 0,

    visual_audio_model: 1,
    audio_smooth_enabled: true,
    audio_smooth_factor: 70,
    audio_spatial_window: 3,
    pw_circle_show_bool: true,
    pw_line_show_bool: true,
    polygon_angle: 1,

    pw_circle_style: 1,
    pw_circle_radius: 50,
    pw_circle_range: 50,
    pw_circle_color: [255, 255, 255] as [number, number, number],
    pw_circle_blur_color: [255, 255, 255] as [number, number, number],
    pw_circle_x: 50,
    pw_circle_y: 50,
    pw_circle_color_mode: 0,
    pw_circle_solid_color_gradient: false,
    pw_circle_blur_color_gradient: false,
    pw_circle_color_rhythm: false,
    pw_circle_gradient_rate: 10,
    pw_circle_line_width: 2,
    pw_circle_rotation: 0,
    pw_circle_direction: 0,
    pw_circle_wavetransparency: 80,
    pw_circle_show_semi_circle: false,
    pw_circle_semicircle_direction: 0,

    pw_line_position: 50,
    pw_line_style: 1,
    pw_line_direction: 0,
    pw_line_width: 2,
    pw_line_spacing: 50,
    pw_line_density: 100,
    pw_line_range: 50,
    pw_line_transparency: 80,
    pw_line_color: [255, 255, 255] as [number, number, number],
    pw_line_blur_color: [255, 255, 255] as [number, number, number],
    pw_line_x: 50,
    pw_line_y: 50,
    pw_line_middle_line: false,
    pw_line_color_mode: 0,
    pw_line_solid_color_gradient: false,
    pw_line_blur_color_gradient: false,
    pw_line_color_rhythm: false,
    pw_line_gradient_rate: 10,

    audio_amplitude: 50,
    audio_decline: 50,
    audio_is_ring: false,
    audio_is_static_ring: false,
    audio_is_inner_ring: false,
    audio_is_outer_ring: false,
    audio_radius: 50,
    audio_ring_rotation: 50,
    audio_opacity: 90,
    audio_color: [255, 255, 255] as [number, number, number],
    audio_shadow_color: [255, 255, 255] as [number, number, number],
    audio_shadow_blur: 75,
    audio_offset_x: 50,
    audio_offset_y: 50,
    audio_is_click_offset: false,
    audio_is_line_to: false,
    audio_first_point: 50,
    audio_second_point: 50,
    audio_point_num: 120,
    audio_distance: 50,
    audio_line_width: 50,
    audio_is_ball: false,
    audio_ball_spacer: 50,
    audio_ball_size: 50,
    audio_ball_rotation: 50,
};

export type AudioVisualDefaults = typeof audioVisualDefaults;
