export const hitokotoDefaults = {
    hitokoto_update: 6,
    hitokoto_init: false,
    hitokoto_format_test: 1,
    hitokoto_size_x_show: null as number | null,
    hitokoto_show: false,
    hitokoto_timetransparency: 100,
    hitokoto_roundedcorners: 0,
    hitokoto_size: 50,
    hitokoto_showwidth: 0,
    hitokoto_x: 50,
    hitokoto_y: 50,

    hit_a: '',
    hit_b: '',
    hit_c: '',
    hit_d: '',
    hit_e: '',
    hit_f: '',
    hit_g: '',
    hit_h: '',
    hit_i: '',
    hit_j: '',
    hit_k: '',
    hit_l: '',

    hitokoto_color: [255, 255, 255] as [number, number, number],
    hitokoto_blurcolor_show: false,
    hitokoto_blurcolor: [255, 255, 255] as [number, number, number],
    hitokoto_yakeli_show: false,
    hitokoto_yakelic_color: [255, 255, 255] as [number, number, number],
    hitokoto_yakeli: 0,
    hitokoto_bluryakeli: 10,
};

export type HitokotoDefaults = typeof hitokotoDefaults;
