export const playerDefaults = {
    player_control_autohide: true,

    player_control_show: false,
    player_control_scalefactor: 1,
    player_control_color: [255, 255, 255] as [number, number, number],
    player_control_blurcolor_show: false,
    player_control_blurcolor: [255, 255, 255] as [number, number, number],
    player_control_yakeli_show: false,
    player_control_yakelic_color: [255, 255, 255] as [number, number, number],
    player_control_yakeli: 0,
    player_control_bluryakeli: 10,
    player_control_thumbnail_size: 0,
    player_control_size_value: 100,
    player_control_thumbnail_size_value: 100,
    player_control_thumbnail_rotation: false,
    player_control_thumbnail_rotation_speed: 5,
    player_control_timetransparency: 1,
    player_control_showwidth: 0,
    player_control_yakelibgusetb: 1,
    player_control_fontusetb: 5,
    player_control_thumbnailrorl: false,
    player_control_samealbum_title: false,
    player_control_visualaudiobar: 0,
    player_control_barline: 0,
    color_pickup_method: 1,
    player_control_hdong: 0.1,
    player_x: 50,
    player_y: 50,
    playery: 80,
    playerx: 50,
    player_control_roundedcorners: 0,
};

export type PlayerDefaults = typeof playerDefaults;
