export {
    apiFetch,
    apiPost,
    clearIconCache,
    fetchAggregate,
    fetchAllIcons,
    fetchAudioMetadata,
    fetchConfig,
    fetchIcon,
    fetchSetup,
    getAudioStreamUrl,
    isApiError,
    listFiles,
    openDockbarItem,
    postMediaAction,
    postSetupAction,
    selectFile,
    updateConfig,
    uploadCustomIcon,
} from './api';
export { getSystemMonitor, initSystemMonitor, SystemMonitor } from './SystemMonitor';
export { buildCards, destroyCards, updateCards } from './cardRenderer';
export type {
    AggregateInfo,
    AllIconItem,
    AllIconsResult,
    ApiErrorResponse,
    // Re-export the comprehensive backend-API types so
    // external consumers (DockBar, property handlers,
    // setup-page code) can pick the shape they need
    // from a single import path.
    ApiResponse,
    ApiStringKey,
    AudioMetadata,
    ClearCacheResponse,
    ConfigView,
    CpuInfo,
    CustomIconRequest,
    CustomIconResponse,
    FileEntry,
    FileListResult,
    GpuInfo,
    IconData,
    MediaAction,
    MediaControlResult,
    MemoryInfo,
    NetworkInfo,
    NetworkInterface,
    OpenItemRequest,
    OpenItemResponse,
    RunMode,
    SelectFileResult,
    SetupActionRequest,
    SetupConfig,
    SetupState,
    SystemInfo,
    SystemMonitorConfig,
    SystemMonitorData,
    SystemMonitorDomRefs,
    SystemMonitorCardDomRefs,
    CardPayload,
    CardMetaEntry,
    SparkChannel,
    CardRenderData,
    TempRange,
    TempComponent,
    TimeInfo,
    UpdateConfigRequest,
} from './types';
