/**
 * Pinia store: config
 *
 * 包覆原 `src/utils/config/index.ts` 的 `AppConfig` 单例，
 * 暴露 `config.xxx` 与 `config.runtime.xxx` 的字段。
 *
 * 属性来源（WE only）：
 *   1. Wallpaper Engine 通过 applyUserProperties 推送（最高优先级）
 *   2. 本 store 初始 state（BUILTIN_DEFAULTS，兜底）
 */

import { defineStore } from 'pinia';

import { type ConfigStoreState } from './types';

/**
 * 内置默认值（兜底中的兜底）。
 * 当三层回退都拿不到值时（例如 project.json 加载失败且 WE 未注入），
 * 落到这些常量上。完整默认值清单见原 `src/utils/config/defaults/*.ts`，
 * 此处仅声明 Phase 1 涉及的字段。
 */
const BUILTIN_DEFAULTS: ConfigStoreState = {
    language: 'zh-CN',
    language_code: 'zh',
    font_setting: '',
    first_load: true,
    paused: false,
    date_init_complete: false,
    bg_init_complete: false,
    weather_init_complete: false,
    fluid_effect_init_complete: false,
    particles_init_complete: false,
    update_init_complete: false,

    time_transparency: 0.8,
    time_x: 50,
    time_y: 50,
    date_format: {
        year_format: 1,
        month_format: 1,
        day_format: 1,
        week_format: 1,
        separator: 1,
        order: 1,
    },
    date_format_test: 1,
    t_show_sencends: true,
    time_color_rhythm: false,
    time_color: 'rgb(255, 255, 255)',
    time_blur_color: '0 0 20px rgb(255, 255, 255)',
    show_time: true,
    time_style: true,
    t_size: 100,
    odate_roundedcorners: 0,
    oclock_roundedcorners: 0,
    date_color_rhythm: false,
    date_color: [255, 255, 255],
    date_transparency: 0.8,
    show_date: true,
    date_x: 50,
    date_y: 45,
    date_size: 100,
    date_showwidth: 0,
    odate_color: [255, 255, 255],
    odate_blurcolor_show: false,
    odate_blurcolor: [255, 255, 255],
    odate_yakeli_show: false,
    odate_yakelic_color: [255, 255, 255],
    odate_yakeli: 0,
    odate_bluryakeli: 10,
    oclock_color: [255, 255, 255],
    oclock_blurcolor_show: false,
    oclock_blurcolor: [255, 255, 255],
    oclock_yakeli_show: false,
    oclock_yakelic_color: [255, 255, 255],
    oclock_yakeli: 0,
    oclock_bluryakeli: 10,

    hitokoto_update: 6,
    hitokoto_init: false,
    hitokoto_format_test: 1,
    hitokoto_size_x_show: null,
    hitokoto_show: false,
    hitokoto_timetransparency: 100,
    hitokoto_roundedcorners: 0,
    hitokoto_size: 50,
    hitokoto_showwidth: 0,
    hitokoto_x: 50,
    hitokoto_y: 50,
    hit_a: '',
    hit_b: '',
    hit_c: '',
    hit_d: '',
    hit_e: '',
    hit_f: '',
    hit_g: '',
    hit_h: '',
    hit_i: '',
    hit_j: '',
    hit_k: '',
    hit_l: '',
    hitokoto_color: [255, 255, 255],
    hitokoto_blurcolor_show: false,
    hitokoto_blurcolor: [255, 255, 255],
    hitokoto_yakeli_show: false,
    hitokoto_yakelic_color: [255, 255, 255],
    hitokoto_yakeli: 0,
    hitokoto_bluryakeli: 10,

    countdown_year: new Date().getFullYear(),
    countdown_month: new Date().getMonth() + 1,
    countdown_day: new Date().getDate(),
    countdown_color: [255, 255, 255],
    countdown_blurcolor_show: false,
    countdown_blurcolor: [255, 255, 255],
    countdown_yakeli_show: false,
    countdown_yakelic_color: [255, 255, 255],
    countdown_yakeli: 0,
    countdown_bluryakeli: 10,
    countdown_txt: '',
    countdown_txt1: '',
    first_load_countdown: true,
    countdown_y: 80,
    countdown_x: 50,
    countdown_size: 50,
    countdown_show: false,
    countdown_timetransparency: 80,
    countdown_roundedcorners: 0,

    // Fullscreen lyrics (Stage 3-1) — defaults from utils/config/defaults/fullscreenLyrics.ts
    fullscreen_lyrics_enabled: false,
    fullscreen_lyrics_show_translation: true,
    fullscreen_lyrics_show_roman: false,
    fullscreen_lyrics_delay: 0,
    fullscreen_lyrics_enable_blur: true,
    fullscreen_lyrics_hide_other: true,
    fullscreen_lyrics_show_clock: false,

    // Weather (Stage 3-2) — defaults from utils/config/defaults/weather.ts
    weather_api_choose: undefined as number | undefined,
    weather_updata: 3,
    weather_unit: 'metric',
    weather_lang: 'en',
    qweather_api_paymode: false,
    city_key: '',
    api_host: '',
    visual_crossing_key: '',
    weather_app_id: '',
    weather_app_secret: '',
    weather_color: [255, 255, 255] as [number, number, number],
    weather_blurcolor_show: false,
    weather_blurcolor: [255, 255, 255] as [number, number, number],
    weather_yakeli_show: false,
    weather_yakelic_color: [255, 255, 255] as [number, number, number],
    weather_yakeli: 0,
    weather_bluryakeli: 10,
    weather_daily_tip: false,
    weather_latitude: '',
    weather_longitude: '',
    weather_city_text: '',
    weather_timetransparency: 80,
    weather_roundedcorners: 10,
    weather_size: 100,
    weather_showwidth: 0,
    weather_x: 50,
    weather_y: 50,

    // Background / wallpaper (Stage 3-3) — defaults from utils/config/defaults/background.ts
    custom: '',
    customdirectory: '',
    wallpaper_mode: 1,
    galaxy_api: 1,
    chiyuanapi: 'https://t.alcy.cc/ycy/?json',
    pictures_url: '',
    select_video: '',
    video_route: '',
    video_model: 1,
    video_model_now: 1,
    cusvideo_route: '',
    cusaudio_route: '',
    // background_route: single-image mode (case 1) 的本地文件路径
    // 之前只在 appConfig 单例中定义；slide/sources/index.ts 迁移到 Pinia 后
    // 需要这个字段在 store 中可读，否则会停在 undefined → 1.jpg 路径丢失。
    background_route: './source/imgs/1.jpg',
    video_volume: 0.5,
    selectmusic: '',
    music_model: 0,
    music_volume: 0.5,
    music_playlist: [] as string[],
    music_playlist_index: 0,
    music_playlist_random: false,
    music_playlist_repeat: 0,
    musicdirectory: '',
    speed: 1,
    slide_now: false,
    switch_interval_input: 60,
    random: 0,
    transition_mode: 1,
    transition_mode_choose_0: false,
    transition_mode_choose_1: false,
    transition_mode_choose_4: false,
    bgx: '512px',
    bgy: '512px',
    bgxy: '512px 512px ',
    bgs: '100%',
    bg_style: 1,
    frist_picturesinfo: true,
    pictures_info_y: 50,
    pictures_info_x: 50,
    pictures_info_size: 30,
    pictures_info_show: null as boolean | null,
    pictures_info_color: null as [number, number, number] | null,
    pictures_info_blurcolor_show: null as boolean | null,
    pictures_info_blurcolor: null as [number, number, number] | null,
    pictures_info_yakeli_show: null as boolean | null,
    pictures_info_yakelic_color: null as [number, number, number] | null,
    pictures_info_yakeli: null as number | null,
    pictures_info_bluryakeli: null as number | null,
    pictures_info_timetransparency: 1,
    pictures_info_roundedcorners: 0,
    pictures_info_showaway: false,
    pictures_info_show_ror_l: null as boolean | null,
    pictures_info_showwidth: 0,
    pictures_info_description: false,

    // Player control (Stage 3-3) — defaults from utils/config/defaults/player.ts
    player_control_show: false,
    player_control_scalefactor: 1,
    player_control_color: [255, 255, 255] as [number, number, number],
    player_control_blurcolor_show: false,
    player_control_blurcolor: [255, 255, 255] as [number, number, number],
    player_control_yakeli_show: false,
    player_control_yakelic_color: [255, 255, 255] as [number, number, number],
    player_control_yakeli: 0,
    player_control_bluryakeli: 10,
    player_control_thumbnail_size: 0,
    player_control_size_value: 100,
    player_control_thumbnail_size_value: 100,
    player_control_thumbnail_rotation: false,
    player_control_thumbnail_rotation_speed: 5,
    player_control_timetransparency: 1,
    player_control_showwidth: 0,
    player_control_yakelibgusetb: 1,
    player_control_fontusetb: 5,
    player_control_thumbnailrorl: false,
    player_control_samealbum_title: false,
    player_control_visualaudiobar: 0,
    player_control_barline: 0,
    color_pickup_method: 1,
    player_control_hdong: 0.1,
    playery: 80,
    playerx: 50,
    player_control_autohide: true,
    player_x: 50,
    player_y: 50,
    player_control_roundedcorners: 0,

    // Sakura (Stage 3-3) — defaults from utils/config/defaults/sakura.ts
    showSakura: true,
    sakura_transparency: 0.15,
    sakura_background: true,
    sakura_back_color: true,
    sakura_reverse: false,
    sakura_point_number: 300,
    sakura_back_light: 0.01,

    // RGB lighting (Stage 3-3) — defaults from utils/config/defaults/rgb.ts
    rgb_show: false,
    background_rgb: false,
    sakura_rgb: false,
    particles_rgb: false,
    audiobar_rgb: false,
    rgb_refresh: 0,
    opacity_sa_rgb: 1,
    aurgbhigh: 1,
    aurgbcolor: '255,255,255',
    audiobar_rainbow_color: false,
    rainbow_move: false,
    rainbow_move_speed: 1,
    nextphoto: false,

    // Fluid effect (Stage 3-3) — defaults from utils/config/defaults/fluid.ts
    // fluid_effect_init_complete is in the legacy init-complete block above
    fluidEffectEnabled: false,
    wallpaper_settings: {
        ledPlugin: false,
        cuePlugin: false,
    } as { ledPlugin: boolean; cuePlugin: boolean },
    fluid_effect_enabled_fullscreen: false,
    fluid_effect_resolution: 240,
    fluid_effect_blur_amount: 20,
    fluid_effect_displacement_scale: 0.5,
    fluid_effect_turbulence_octaves: 4,
    fluid_effect_canvas_displacement: 0,
    fluid_effect_dark_overlay_strength: 50,
    fluid_effect_backdrop_filter_strength: 10,

    // Particle effect (Stage 3-3) — defaults from utils/config/defaults/particle.ts
    // particles_init_complete is set in useParticleProperties
    particles_is_particles: false,
    particles_number: 100,
    particles_opacity: 100,
    particles_opacity_random: false,
    particles_color: [255, 255, 255] as [number, number, number],
    particles_shadow_color: [255, 255, 255] as [number, number, number],
    particles_shadow_blur: 10,
    particles_image: '',
    particles_shape_type: 1,
    map_route: './source/map/1.png',
    particles_size_value: 10,
    particles_size_random: false,
    particles_link_enable: false,
    particles_link_distance: 50,
    particles_link_width: 1,
    particles_link_color: [255, 255, 255] as [number, number, number],
    particles_link_opacity: 50,
    particles_is_move: true,
    particles_speed: 1,
    particles_speed_random: false,
    particles_direction: 1,
    particles_is_straight: false,
    particles_is_bounce: false,
    particles_move_out_mode: 1,

    // AudioVisual (Stage 3-3) — defaults from utils/config/defaults/audioVisual.ts
    visual_audio_model: 1,
    audio_smooth_enabled: true,
    audio_smooth_factor: 70,
    audio_spatial_window: 3,
    pw_circle_show_bool: true,
    pw_line_show_bool: true,
    polygon_angle: 1,

    pw_circle_style: 1,
    pw_circle_radius: 50,
    pw_circle_range: 50,
    pw_circle_color: [255, 255, 255] as [number, number, number],
    pw_circle_blur_color: [255, 255, 255] as [number, number, number],
    pw_circle_x: 50,
    pw_circle_y: 50,
    pw_circle_color_mode: 0,
    pw_circle_solid_color_gradient: false,
    pw_circle_blur_color_gradient: false,
    pw_circle_color_rhythm: false,
    pw_circle_gradient_rate: 10,
    pw_circle_line_width: 2,
    pw_circle_rotation: 0,
    pw_circle_direction: 0,
    pw_circle_wavetransparency: 80,
    pw_circle_show_semi_circle: false,
    pw_circle_semicircle_direction: 0,

    pw_line_position: 50,
    pw_line_style: 1,
    pw_line_direction: 0,
    pw_line_width: 2,
    pw_line_spacing: 50,
    pw_line_density: 100,
    pw_line_range: 50,
    pw_line_transparency: 80,
    pw_line_color: [255, 255, 255] as [number, number, number],
    pw_line_blur_color: [255, 255, 255] as [number, number, number],
    pw_line_x: 50,
    pw_line_y: 50,
    pw_line_middle_line: false,
    pw_line_color_mode: 0,
    pw_line_solid_color_gradient: false,
    pw_line_blur_color_gradient: false,
    pw_line_color_rhythm: false,
    pw_line_gradient_rate: 10,

    audio_amplitude: 50,
    audio_decline: 50,
    audio_is_ring: false,
    audio_is_static_ring: false,
    audio_is_inner_ring: false,
    audio_is_outer_ring: false,
    audio_radius: 50,
    audio_ring_rotation: 50,
    audio_opacity: 90,
    audio_color: [255, 255, 255] as [number, number, number],
    audio_shadow_color: [255, 255, 255] as [number, number, number],
    audio_shadow_blur: 75,
    audio_offset_x: 50,
    audio_offset_y: 50,
    audio_is_click_offset: false,
    audio_is_line_to: false,
    audio_first_point: 50,
    audio_second_point: 50,
    audio_point_num: 120,
    audio_distance: 50,
    audio_line_width: 50,
    audio_is_ball: false,
    audio_ball_spacer: 50,
    audio_ball_size: 50,
    audio_ball_rotation: 50,

    // === 补充字段 ===
    server_mode: false,
    sysmon_enabled: false,
    sysmon_server_port: 27420,
    wallpaper_updata: false,
    wallpaper_updata_open_on_update: true,
};

export const useConfigStore = defineStore('config', {
    state: (): ConfigStoreState => ({
        ...BUILTIN_DEFAULTS,
    }),
    actions: {
        /**
         * 把 WE 推送的 properties 合并进 state。
         * 由 useWallpaperProperties composable 在 WE 推送时调用。
         */
        applyUserProperties(values: Record<string, { value: unknown }>): void {
            for (const [k, v] of Object.entries(values)) {
                if (k in this.$state && v && 'value' in v) {
                     
                    (this as any).$patch({ [k]: (v as { value: unknown }).value });
                }
            }
        },
    },
});
