/**
 * 天气相关 DOM 元素
 */
export const weatherElements = {
    weather: document.querySelector('#weather') as HTMLElement,
    container: document.querySelector('#weather .weather-container') as HTMLElement,
    leftContainer: document.querySelector('.weather-left') as HTMLElement | null,
    rightContainer: document.querySelector('.weather-right') as HTMLElement | null,
    icon: document.getElementById('weatherIcon') as HTMLElement,
    temp: document.getElementById('weatherTemp') as HTMLElement,
    text: document.getElementById('weatherText') as HTMLElement,
    feels: document.getElementById('weatherFeels') as HTMLElement,
    city: document.getElementById('weatherCity') as HTMLElement,
    tempRange: document.getElementById('weatherTempRange') as HTMLElement,
    humidity: document.getElementById('weatherHumidity') as HTMLElement,
    windDirection: document.getElementById('weatherWindDirection') as HTMLElement,
    windLevel: document.getElementById('weatherWindLevel') as HTMLElement,
    windSpeed: document.getElementById('weatherWindSpeed') as HTMLElement,
    visibility: document.getElementById('weatherVisibility') as HTMLElement,
    detailRow: document.getElementById('weatherDetailRow') as HTMLElement,
    uvIndex: document.getElementById('weatherUvIndex') as HTMLElement,
    cloud: document.getElementById('weatherCloud') as HTMLElement,
    sunrise: document.getElementById('weatherSunrise') as HTMLElement,
    sunset: document.getElementById('weatherSunset') as HTMLElement,
    moonphase: document.getElementById('weatherMoonphase') as HTMLElement,
    airRow: document.getElementById('weatherAirRow') as HTMLElement,
    airQuality: document.getElementById('weatherAirQuality') as HTMLElement,
    airValue: document.getElementById('weatherAirValue') as HTMLElement,
    alertContainer: document.getElementById('weatherAlertContainer') as HTMLElement,
    precipContainer: document.getElementById('weatherPrecipContainer') as HTMLElement,
    precipLabel: document.getElementById('weatherPrecipLabel') as HTMLElement,
    precipTimes: document.getElementById('weatherPrecipTimes') as HTMLElement,
    precipValues: document.getElementById('weatherPrecipValues') as HTMLElement,
    tip: document.getElementById('weatherTip') as HTMLElement,
} as const;
